### Section A: Data Structures & Control Structures ###

In [1]:
a=[5,4,3,2,1]
print("Orginal List",a)

a.sort()
print("Sorted List",a)

a.append(6)
print("Appended List",a)

a.extend([7,8])
print("Extended List",a)

a.insert(8,9)
print("Inserted List",a)

a.remove(2)
print("Removed List",a)

a.pop()
print("Pop List",a)

##INDEX##
print("Index",a.index(4))

##COUNT##
print("count",a.count(8))

##REVERSE LIST
print("Reveresed List",a[::-1])

##CLEARED LIST##
a.clear()
print("clearded List",a)

Orginal List [5, 4, 3, 2, 1]
Sorted List [1, 2, 3, 4, 5]
Appended List [1, 2, 3, 4, 5, 6]
Extended List [1, 2, 3, 4, 5, 6, 7, 8]
Inserted List [1, 2, 3, 4, 5, 6, 7, 8, 9]
Removed List [1, 3, 4, 5, 6, 7, 8, 9]
Pop List [1, 3, 4, 5, 6, 7, 8]
Index 2
count 1
Reveresed List [8, 7, 6, 5, 4, 3, 1]
clearded List []


In [2]:
students=("Neela","Divya","Sangu")
print(type(students))
print("Orginal Tuple",students)

print(students[1])

students[2]="Sahana"
'''--> Tuples are immutable data types in python it means we cannot do the following.
a) ADD
b) DELETE
c) MODIFY 
--> It is commonly called as read only version of LIST , Indexing is possible'''

<class 'tuple'>
Orginal Tuple ('Neela', 'Divya', 'Sangu')
Divya


TypeError: 'tuple' object does not support item assignment

In [3]:
a={21,24,1,12,5,28,21,1,5}
print(type(a))
print("SET",a)

# a) SET is Unordered
# b) SET stores UNIQUE elements only
# c) SET automatically deletes duplicates

<class 'set'>
SET {1, 5, 21, 24, 12, 28}


In [4]:
DICT1={'name':"Sangu",
       'age':23,
       'city':"Bengaluru"
      }

print(type(DICT1))
print(DICT1)

DICT1['age']=24
print(DICT1)

DICT1['email']="sanguhsandy@gmail.com"
print("Updated Dictionary",DICT1)

<class 'dict'>
{'name': 'Sangu', 'age': 23, 'city': 'Bengaluru'}
{'name': 'Sangu', 'age': 24, 'city': 'Bengaluru'}
Updated Dictionary {'name': 'Sangu', 'age': 24, 'city': 'Bengaluru', 'email': 'sanguhsandy@gmail.com'}


In [5]:
age=int(input("Enter age"))
if age<=18:
    print("Not Eligible For Voting")
else:
    print("Eligible For Voting")
    
    

Enter age 45


Eligible For Voting


In [6]:
marks=int(input("Enter the Marks"))
if marks>=90:
    print('Grade:A')
elif marks>=75:
    print('Grade:B')
elif marks>=50:
    print('Grade:C')
else:
    print('Fail')

Enter the Marks 45


Fail


In [7]:
def number(n):
    if n>0:
        if n%2==0:
            print("The num is positive and Even",n)
        else:
            print("The num is positive and odd",n)
    elif n==0:
        print("The num is Zer",n)
    else:
        print("The num is negative",n)
number(-2)


The num is negative -2


### Section B: Numpy ##

In [8]:
import numpy as np
scalar=np.array(5)
print("Scalar")
print(scalar)


array_1=np.array([1,2,3,4,5])
print("One Dimensional Array",array_1)


array_2=np.arange(10,70,10).reshape(2,3)
print("Two Dimensional Array")
print(array_2)

Scalar
5
One Dimensional Array [1 2 3 4 5]
Two Dimensional Array
[[10 20 30]
 [40 50 60]]


In [9]:
import numpy as np
array_random=np.random.randint(0,101,size=(4,4))
print("Random Array")
print(array_random)
                      

Random Array
[[ 32  24  77  97]
 [ 22   7  34  83]
 [ 60  53  39  66]
 [ 23  56   8 100]]


In [10]:
import pandas as pd
import numpy as np
array_2d=np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("Two_Dimensional_Array")
print(array_2d)

data=pd.DataFrame(array_2d,columns=['A','B','C'])
data

Two_Dimensional_Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


,A,B,C
0,1,2,3
1,4,5,6
2,7,8,9


### Section C: Exploring Pandas ##

In [11]:
import pandas as pd
data={
    'Name':["sangu","harshitha","arpitha","neela","divya","vijju","Anu","China","ramya","bhoomu"],
    
    'Age':[23,21,20,None,None,23,21,20,None,None],
    'salary':[20000,30000,None,None,40000,20000,30000,None,None,40000],
    'city':["bengaluru","Hyderabad","gangavathi","hubli","Koppal","bengaluru","Hyderabad","gangavathi","hubli","Koppal"]
}
data=pd.DataFrame(data)
print("Orginal Data")
data

Orginal Data


,Name,Age,salary,city
0,sangu,23.0,20000.0,bengaluru
1,harshitha,21.0,30000.0,Hyderabad
2,arpitha,20.0,NaN,gangavathi
3,neela,NaN,NaN,hubli
4,divya,NaN,40000.0,Koppal
5,vijju,23.0,20000.0,bengaluru
6,Anu,21.0,30000.0,Hyderabad
7,China,20.0,NaN,gangavathi
8,ramya,NaN,NaN,hubli
9,bhoomu,NaN,40000.0,Koppal


In [12]:
data.head()

,Name,Age,salary,city
0,sangu,23.0,20000.0,bengaluru
1,harshitha,21.0,30000.0,Hyderabad
2,arpitha,20.0,NaN,gangavathi
3,neela,NaN,NaN,hubli
4,divya,NaN,40000.0,Koppal


In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     6 non-null      float64
 2   salary  6 non-null      float64
 3   city    10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [14]:
data.describe()

,Age,salary
count,6.000000,6.00000
mean,21.333333,30000.00000
std,1.366260,8944.27191
min,20.000000,20000.00000
25%,20.250000,22500.00000
50%,21.000000,30000.00000
75%,22.500000,37500.00000
max,23.000000,40000.00000


In [15]:
selected_col=data[['Name','city']]
print("selected_columns")

selected_columns


In [16]:
data_droped=data.drop('city',axis=1)
data_droped

,Name,Age,salary
0,sangu,23.0,20000.0
1,harshitha,21.0,30000.0
2,arpitha,20.0,NaN
3,neela,NaN,NaN
4,divya,NaN,40000.0
5,vijju,23.0,20000.0
6,Anu,21.0,30000.0
7,China,20.0,NaN
8,ramya,NaN,NaN
9,bhoomu,NaN,40000.0


In [17]:
data.isnull().sum()

Name      0
Age       4
salary    4
city      0
dtype: int64

In [18]:
data['Age'].fillna(data['Age'].mean(),inplace=True)
data['salary'].fillna(data['salary'].mean(),inplace=True)
data

C:\Users\sangu\AppData\Local\Temp\ipykernel_23480\2128934575.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].fillna(data['Age'].mean(),inplace=True)
C:\Users\sangu\AppData\Local\Temp\ipykernel_23480\2128934575.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For 

,Name,Age,salary,city
0,sangu,23.000000,20000.0,bengaluru
1,harshitha,21.000000,30000.0,Hyderabad
2,arpitha,20.000000,30000.0,gangavathi
3,neela,21.333333,30000.0,hubli
4,divya,21.333333,40000.0,Koppal
5,vijju,23.000000,20000.0,bengaluru
6,Anu,21.000000,30000.0,Hyderabad
7,China,20.000000,30000.0,gangavathi
8,ramya,21.333333,30000.0,hubli
9,bhoomu,21.333333,40000.0,Koppal


In [19]:
data.isnull().sum()

Name      0
Age       0
salary    0
city      0
dtype: int64

In [20]:
duplicated=data[data.duplicated()]
duplicated

,Name,Age,salary,city


In [21]:
data_no_duplicates = data.drop_duplicates()
print("After Removing Duplicates")
data

After Removing Duplicates


,Name,Age,salary,city
0,sangu,23.000000,20000.0,bengaluru
1,harshitha,21.000000,30000.0,Hyderabad
2,arpitha,20.000000,30000.0,gangavathi
3,neela,21.333333,30000.0,hubli
4,divya,21.333333,40000.0,Koppal
5,vijju,23.000000,20000.0,bengaluru
6,Anu,21.000000,30000.0,Hyderabad
7,China,20.000000,30000.0,gangavathi
8,ramya,21.333333,30000.0,hubli
9,bhoomu,21.333333,40000.0,Koppal
